global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'rims-monitor'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - System metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'rims-server'

  # MySQL Exporter
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql_exporter:9104']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'rims-mysql'

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'rims-redis'

  # Nginx Exporter
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx_exporter:9113']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'rims-nginx'

  # Laravel Application Metrics (if exposed)
  - job_name: 'laravel'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:9000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'rims-app'