version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: rims_app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "5173:5173"
    volumes:
      - ./src:/var/www/html
    networks:
      - rims_network
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: rims_webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default-dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - rims_network
    depends_on:
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rims.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.rims.entrypoints=websecure"
      - "traefik.http.routers.rims.tls=true"
      - "traefik.http.routers.rims.middlewares=security-headers"
      - "traefik.http.services.rims.loadbalancer.server.port=80"
      - "traefik.docker.network=rims_network"

  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: rims_db
    restart: unless-stopped
    ports:
      - "3308:3306"
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    networks:
      - rims_network


volumes:
  dbdata:
    driver: local

networks:
  rims_network:
    driver: bridge